"""New initial migration after going to hell with order being related with 2 users, buyer and delivery guy

Revision ID: 18a4fb017bad
Revises: 
Create Date: 2024-05-17 11:48:24.557900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18a4fb017bad'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('_password_hash', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=True),
    sa.Column('contact', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_banda_admin', sa.Boolean(), nullable=True),
    sa.Column('is_banda_delivery', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('delivery_fee', sa.String(), nullable=True),
    sa.Column('delivery_person', sa.Integer(), nullable=True),
    sa.Column('delivery_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], name=op.f('fk_order_buyer_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('logo_image_url', sa.String(), nullable=False),
    sa.Column('banner_image_url', sa.String(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name=op.f('fk_shop_seller_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name=op.f('fk_product_shop_id_shop')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('fk_order_item_order_id_order')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_order_item_product_id_product')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_products_images_product_id_product')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('buyer_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['user.id'], name=op.f('fk_review_buyer_id_user')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_review_product_id_product')),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], name=op.f('fk_review_seller_id_user')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    op.drop_table('products_images')
    op.drop_table('order_item')
    op.drop_table('product')
    op.drop_table('shop')
    op.drop_table('order')
    op.drop_table('user')
    # ### end Alembic commands ###