"""Added Delivery fee column

Revision ID: 26937f1c70af
Revises: 84c78e8d1e30
Create Date: 2024-05-15 08:29:32.771280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26937f1c70af'
down_revision = '84c78e8d1e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_fee', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_fee')

    # ### end Alembic commands ###
