"""Added transactions table with no relationships

Revision ID: 36f06e85d4cb
Revises: de1f444c8f8a
Create Date: 2024-05-19 23:59:32.240768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36f06e85d4cb'
down_revision = 'de1f444c8f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MpesaReceiptNumber', sa.String(), nullable=True),
    sa.Column('Amount', sa.Integer(), nullable=True),
    sa.Column('TransactionDate', sa.Integer(), nullable=True),
    sa.Column('PhoneNumber', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    # ### end Alembic commands ###