"""Added likedproduct table and followedshop table

Revision ID: 384ee24c65cb
Revises: 36f06e85d4cb
Create Date: 2024-05-20 13:55:19.573789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384ee24c65cb'
down_revision = '36f06e85d4cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followed_shop',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyers_id', sa.Integer(), nullable=True),
    sa.Column('shop_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyers_id'], ['user.id'], name=op.f('fk_followed_shop_buyers_id_user')),
    sa.ForeignKeyConstraint(['shop_id'], ['shop.id'], name=op.f('fk_followed_shop_shop_id_shop')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('liked_product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('buyers_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['buyers_id'], ['user.id'], name=op.f('fk_liked_product_buyers_id_user')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_liked_product_product_id_product')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('liked_product')
    op.drop_table('followed_shop')
    # ### end Alembic commands ###