"""Changed delivery person to persons

Revision ID: 49b3e009e5e0
Revises: ae9cb5083df0
Create Date: 2024-05-22 10:28:56.460455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49b3e009e5e0'
down_revision = 'ae9cb5083df0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_persons', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_persons')

    # ### end Alembic commands ###
