"""Added date to order and review

Revision ID: 6de71214d044
Revises: 9a55ecfd2724
Create Date: 2024-05-17 09:23:06.186449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de71214d044'
down_revision = '9a55ecfd2724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('delivery_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_order_delivery_id_user'), 'user', ['delivery_id'], ['id'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('date')

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_order_delivery_id_user'), type_='foreignkey')
        batch_op.drop_column('delivery_id')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
