"""Added columns from mike branch without recurssion errors

Revision ID: 73961c1c32fa
Revises: 8b4173edd7ce
Create Date: 2024-05-18 01:18:02.144993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73961c1c32fa'
down_revision = '8b4173edd7ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buyers_id', sa.Integer(), nullable=True))
        batch_op.alter_column('delivery_address',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.drop_constraint('fk_order_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_order_buyers_id_user'), 'user', ['buyers_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_order_delivery_id_user'), 'user', ['delivery_id'], ['id'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_order_delivery_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_order_buyers_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_order_user_id_user', 'user', ['user_id'], ['id'])
        batch_op.alter_column('delivery_address',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('buyers_id')

    # ### end Alembic commands ###
