"""removed seller_id from product table

Revision ID: 84c78e8d1e30
Revises: ab884038fe3f
Create Date: 2024-05-14 02:12:12.020752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c78e8d1e30'
down_revision = 'ab884038fe3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_seller_id_user', type_='foreignkey')
        batch_op.drop_column('seller_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_product_seller_id_user', 'user', ['seller_id'], ['id'])

    # ### end Alembic commands ###
