"""Removed delivery and user relationship

Revision ID: 8b4173edd7ce
Revises: 6de71214d044
Create Date: 2024-05-17 10:41:19.502933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4173edd7ce'
down_revision = '6de71214d044'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint('fk_order_delivery_id_user', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_order_delivery_id_user', 'user', ['delivery_id'], ['id'])

    # ### end Alembic commands ###
