"""Added is new seller column to user with default as true

Revision ID: 90d131e69dc1
Revises: 55d6fdaab278
Create Date: 2024-05-27 12:58:38.643933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90d131e69dc1'
down_revision = '55d6fdaab278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_new_seller', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_new_seller')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
