"""delivery person from delivery id in order

Revision ID: a409261f8633
Revises: 2eb835ed1bff
Create Date: 2024-05-17 11:06:00.469524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a409261f8633'
down_revision = '2eb835ed1bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_person', sa.Integer(), nullable=True))
        batch_op.drop_column('date')
        batch_op.drop_column('delivery_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.INTEGER(), nullable=True))
        batch_op.drop_column('delivery_person')

    # ### end Alembic commands ###
