"""Added more fields to order table

Revision ID: c774e6fe0269
Revises: 384ee24c65cb
Create Date: 2024-05-22 12:34:08.850802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c774e6fe0269'
down_revision = '384ee24c65cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delivery_persons', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('delivery_persons')
        batch_op.drop_column('city')
        batch_op.drop_column('country')
        batch_op.drop_column('name')
        batch_op.drop_column('contact')

    # ### end Alembic commands ###
