"""Added Specification table

Revision ID: e9173e925e2b
Revises: 90d131e69dc1
Create Date: 2024-05-27 14:29:43.371676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9173e925e2b'
down_revision = '90d131e69dc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spec', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_specification_product_id_product')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specification', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('specification')

    op.drop_table('specification')
    # ### end Alembic commands ###
